---
name: fw-fe
services:
  fw-fe:
    restart: "no"
    image: "node:22.14.0-bookworm"
    container_name: fw-fe
    command: bash -c 'npm install && npm run dev'
    working_dir: /app
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - next_cache:/app/cache
    environment:
      TZ: Europe/Amsterdam
    ports:
      - "3000:3000"

## Volumes inside Docker for cache and npm moules folder to keep git repo clean
volumes:
  node_modules: {}
  next_cache: {}
